name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🧪 Run tests and generate report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pydeps
        pytest > pytest_report.txt || true
        pydeps . --output=deps.svg --max-bacon=3 || true
        mkdir -p report
        cp pytest_report.txt deps.svg report/
        cp report/index.html report/index.html  # 确保页面存在

    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./report
        publish_branch: gh-pages
